const favicon=document.createElement('link');favicon.rel='icon';favicon.type='image/svg+xml';favicon.href='assets/favicon-np.svg';document.head.append(favicon);
const projects={xr:[
{name:'MyTvR — CinemaVR',desc:'An immersive virtual cinema application for streaming and watching content inside Oculus VR environments.',tags:['XR/VR','Unity'],art:'cinemavr',video:'assets/MyTvR.mp4',url:'project-mytvr-cinemavr.html'},
{name:'PopShot',desc:'An experimental XR/VR game built to explore VR interaction systems, interactive objects, UI, and gameplay in Unity.',tags:['XR/VR','Simulation'],art:'video-popshot',video:'assets/PopShot.mp4',poster:'assets/PopShot-midpoint.png',url:'project-popshot.html'},
{name:'RecoVR',desc:'A VR experience designed to help people gradually become more comfortable with fear of heights through controlled virtual exposure.',tags:['XR/VR','Training'],art:'video-recovr',video:'assets/Recovr.mp4',poster:'assets/Recovr-midpoint.png',url:'project-recovr.html'},
{name:'RageRooms',desc:'A VR experience where players smash everyday office objects with a baseball bat using physical interactions and impact feedback.',tags:['XR/VR','Game'],art:'video-ragerooms',video:'assets/RageRooms.mp4',poster:'assets/RageRooms-midpoint.png',url:'project-ragerooms.html'},
{name:'Freaky Frog',desc:'A 3D survival game where a frog collects flies for points while being chased by a predatory bird.',tags:['Game'],art:'video-freakyfrog',video:'assets/FreakyFrog.mp4',poster:'assets/FreakyFrog-midpoint.png',url:'project-freaky-frog.html'},
{name:'Archery Rush',desc:'A time-based archery game where the player aims at moving targets and scores points before the timer runs out.',tags:['Game'],art:'video-archerygame',video:'assets/ArcheryGame.mp4',poster:'assets/ArcheryGame-midpoint.png',url:'project-archery-rush.html'},
{name:'Church Scene',desc:'A cinematic Unity walkthrough of a detailed church environment created to explore real-time rendering and lighting.',tags:['Walkthrough'],art:'video-church',video:'assets/The Church Scene.mp4',poster:'assets/ChurchScene-midpoint.png',url:'project-church-scene.html'}],
unity:[
{name:'Unity Project Placeholder',desc:'Add a verified Unity game, simulation or application here.',tags:['Unity','Coming soon'],art:'unity1',url:'#'},
{name:'Simulation Placeholder',desc:'Reserve this space for a Unity simulation case study.',tags:['Unity','Simulation'],art:'unity2',url:'#'},
{name:'Experiment Placeholder',desc:'A future place for a tool or interactive experiment.',tags:['Unity','Experiment'],art:'unity3',url:'#'}]};
const nav=[['Home','index.html','home'],['XR / Unity Projects','xr-projects.html','xr'],['Teaching','courses.html','courses'],['Contact','contact.html','contact']];
const page=document.body.dataset.page;
document.querySelector('#site-nav').innerHTML=`<nav class="nav"><a class="brand" href="index.html">Nikhil’s Portfolio<span>.</span></a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="mobile-nav-menu" aria-label="Open navigation menu"><span></span><span></span><span></span></button><div class="nav-links" id="mobile-nav-menu">${nav.map(([label,url,id])=>`<a href="${url}" class="${page===id?'active':''}">${label}</a>`).join('')}<a class="button mobile-contact" href="contact.html">Let’s Connect <span>→</span></a></div><a class="button desktop-contact" href="contact.html">Let’s Connect <span>→</span></a></nav>`;
const navToggle=document.querySelector('.nav-toggle');const navLinks=document.querySelector('.nav-links');navToggle?.addEventListener('click',()=>{const isOpen=navLinks.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(isOpen));navToggle.setAttribute('aria-label',isOpen?'Close navigation menu':'Open navigation menu')});
document.querySelector('#site-footer').innerHTML=`<footer class="footer"><div class="wrap"><span>© 2026 XR / Nikhil’s Portfolio</span><span>Engineering immersive experiences</span></div></footer>`;
function card(p){const media=p.video?`<video class="project-video" muted loop playsinline preload="none" poster="${p.poster||''}"><source src="${p.video}" type="video/mp4"></video>`:'';return `<article class="card" data-tags="${p.tags.join('|')}"><div class="project-art ${p.art}">${media}</div><div class="card-body"><div class="card-title-row"><h3>${p.name}</h3><a class="arrow" href="${p.url}" aria-label="View ${p.name}">→</a></div><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div></article>`}
const featured=document.querySelector('#featured-projects');if(featured)featured.innerHTML=projects.xr.slice(0,3).map(card).join('');
const xr=document.querySelector('#xr-projects');if(xr)xr.innerHTML=projects.xr.map(card).join('');const unity=document.querySelector('#unity-projects');if(unity)unity.innerHTML=projects.unity.map(card).join('');
const projectVideos=[...document.querySelectorAll('.project-video')];const hydratePreview=video=>{if(video.dataset.previewLoaded)return;video.dataset.previewLoaded='true';video.preload='metadata';video.addEventListener('loadedmetadata',()=>{if(Number.isFinite(video.duration)&&video.duration>0)video.currentTime=video.duration/2},{once:true});video.addEventListener('seeked',()=>video.classList.add('ready'),{once:true});video.load()};if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){hydratePreview(entry.target);observer.unobserve(entry.target)}}),{rootMargin:'220px'});projectVideos.forEach(video=>observer.observe(video))}else{projectVideos.forEach((video,index)=>setTimeout(()=>hydratePreview(video),index*180))}projectVideos.forEach(video=>{const projectCard=video.closest('.card');projectCard?.addEventListener('mouseenter',()=>{hydratePreview(video);if(video.readyState>=2){video.currentTime=0;video.play()}else video.addEventListener('loadeddata',()=>{video.currentTime=0;video.play()},{once:true})});projectCard?.addEventListener('mouseleave',()=>{video.pause();if(video.readyState>=2)video.currentTime=video.duration/2})});
document.querySelectorAll('.filters button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(b=>b.classList.remove('active'));button.classList.add('active');const filter=button.dataset.filter;document.querySelectorAll('#xr-projects .card').forEach(project=>{project.hidden=filter!=='all'&&!project.dataset.tags.split('|').includes(filter)})}));
const courses=document.querySelector('#courses');if(courses){const courseData=[
{title:'Game Development 2026 : Build an Archery Game with Unity',desc:'I designed and taught a hands-on Unity game-development course where I built an archery game from the ground up, covering gameplay systems, C# programming, aiming, scoring, timing, and player feedback.',art:'course-archery',img:'assets/ArcheryGame.png'},
{title:'Materials In Unity | A Secret Ingredient for Photorealism',desc:'I created a practical Unity materials course focused on building photorealistic surfaces and teaching how shaders, textures, and material properties shape a scene.',art:'course-materials',img:'assets/MaterialsInUnityCourseProfileImage.png'},
{title:'Lighting In Unity | The Art of Lighting for Games',desc:'I created a Unity lighting course showing how I build mood, readability, and visual hierarchy in game environments through lighting setups and scene composition.',art:'course-lighting',img:'assets/LightingInUnity.png'},
{title:'Blender 3D : The Ultimate Guide to 3D Modelling',desc:'I created a beginner-friendly Blender course that teaches a complete 3D modelling workflow, from foundational tools through a finished asset.',art:'course-blender'},
{title:'Game Development 2026 | Build and Share your first 3D Game',desc:'I created a Unity 3D game-development course that takes learners from a blank project to a playable game, covering programming, scene building, and sharing a finished result.',art:'course-3dgame',img:'assets/BuildAndShare.png'}
];courses.innerHTML=courseData.map(c=>`<article class="course"><div class="course-art ${c.art}">${c.img?`<img src="${c.img}" alt="${c.title} course image">`:''}</div><h3>${c.title}</h3><p>${c.desc}</p><a class="button secondary" href="https://www.udemy.com/user/nikhil-kap/" target="_blank" rel="noopener">View on Udemy ↗</a></article>`).join('')+`<div class="learner-count course-learner-card"><strong>2,500+</strong><span>Learners</span><small>Udemy Partner</small></div>`}
